# Generated by Django 3.1.1 on 2020-12-14 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gachon_flea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='학번')),
                ('wallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wallet')),
                ('good', models.IntegerField(default=0, verbose_name='좋아요')),
                ('bad', models.IntegerField(default=0, verbose_name='싫어요')),
                ('record_bad', models.IntegerField(default=0, verbose_name='초기화싫어요')),
                ('black', models.BooleanField(default=False, verbose_name='블랙리스트')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
